import { expect, test } from "@playwright/test";
import { shortArticleHtml, shortBody, shortTitle } from "./fixtures";
import { expectPreviewReady, importRichArticle, mainEditor } from "./helpers";

test("the real loopback helper receives generated PNGs and returns a per-account draft receipt", async ({ page }, testInfo) => {
  test.setTimeout(240000);
  await page.addInitScript(() => localStorage.setItem("zhepage-guide-seen-v1", "1"));
  await page.goto("/");
  await expect(mainEditor(page)).toBeVisible();
  await importRichArticle(page, shortArticleHtml, shortTitle + shortBody);
  await expectPreviewReady(page);
  await page.getByRole("button", { name: "同步草稿", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "同步到平台草稿", exact: true });
  await dialog.getByRole("button", { name: "用当前海报开始", exact: true }).click();
  await expect(dialog.locator(".draft-sync-image-card").first()).toBeVisible({ timeout: 110000 });
  await dialog.locator(".draft-sync-platforms").getByRole("button", { name: /^公众号贴图/ }).click();
  await dialog.getByLabel("公众号贴图标题", { exact: true }).fill("本机 HTTP 整链路");
  await dialog.getByLabel("公众号贴图文案", { exact: true }).fill("测试素材仅交给回环地址上的模拟平台适配器。");
  await dialog.getByRole("button", { name: "下一步：选择账号", exact: true }).click();
  await expect(dialog.getByText("先打开本机版，才能连接账号", { exact: true })).toBeVisible();
  // Launchers may reopen an existing tab with a fragment instead of reloading
  // its document. The existing dialog must accept the handoff without losing edits.
  await page.evaluate(() => { location.hash = "zhepage-pairing=browser-test-pairing-code-only-not-a-real-secret"; });
  await expect(dialog.getByText("本机同步已就绪", { exact: true })).toBeVisible();
  await expect.poll(() => new URL(page.url()).hash).toBe("");
  await expect(dialog.getByLabel("本机助手配对码", { exact: true })).not.toBeVisible();
  await dialog.getByText("需公众号管理员完成首次配置", { exact: true }).click();
  await dialog.getByLabel("账号备注（选填）", { exact: true }).fill("回环接口测试公众号");
  await dialog.getByLabel("公众号 AppID", { exact: true }).fill("wx1234567890abcdef");
  await dialog.getByLabel("公众号 AppSecret", { exact: true }).fill("synthetic-test-secret-only");
  await dialog.getByRole("button", { name: "验证并添加公众号", exact: true }).click();
  const account = dialog.getByRole("checkbox", { name: /回环接口测试公众号/ });
  await expect(account).toBeVisible();
  await expect(dialog.getByLabel("公众号 AppSecret", { exact: true })).toHaveValue("");
  await account.check();
  await dialog.getByRole("checkbox", { name: "我已核对图片，沿用当前尺寸和比例", exact: true }).check();
  await dialog.getByRole("button", { name: "存到 1 个账号草稿", exact: true }).click();
  await expect(dialog.getByText("已保存平台草稿", { exact: true })).toBeVisible({ timeout: 30000 });
  await expect(dialog.getByText("草稿编号：test-only-verified-draft", { exact: true })).toBeVisible();
  await dialog.getByRole("button", { name: "返回选择账号", exact: true }).click();
  await expect(account).not.toBeChecked();
  await dialog.getByRole("button", { name: "查看保存结果", exact: true }).click();
  const persistence = await page.evaluate(() => JSON.stringify({ local: { ...localStorage }, session: { ...sessionStorage } }));
  expect(persistence).not.toContain("synthetic-test-secret-only");
  expect(persistence).not.toContain("browser-test-pairing-code-only-not-a-real-secret");
  await dialog.getByText("草稿编号：test-only-verified-draft", { exact: true }).scrollIntoViewIfNeeded();
  await testInfo.attach("draft-sync-account-result", { body: await page.screenshot(), contentType: "image/png" });
});

test("a fresh launcher page keeps its connection after removing the startup fragment", async ({ page }) => {
  const requests: string[] = [];
  page.on("request", (request) => {
    if (request.url() === "http://127.0.0.1:47831/api/accounts" && request.method() === "GET") requests.push(request.headers().authorization);
  });
  await page.addInitScript(() => localStorage.setItem("zhepage-guide-seen-v1", "1"));
  await page.goto("/#zhepage-pairing=browser-test-pairing-code-only-not-a-real-secret");
  await expect(mainEditor(page)).toBeVisible();
  await expect.poll(() => new URL(page.url()).hash).toBe("");
  expect(requests).toEqual([]);
  await page.getByRole("button", { name: "同步草稿", exact: true }).click();
  await expect.poll(() => requests.length).toBe(1);
  expect(requests[0]).toBe("Bearer browser-test-pairing-code-only-not-a-real-secret");
  const storage = await page.evaluate(() => JSON.stringify({ local: { ...localStorage }, session: { ...sessionStorage } }));
  expect(storage).not.toContain("browser-test-pairing-code-only-not-a-real-secret");
});

test("a pending login can be edited around, cancelled through the real helper, and retried", async ({ page }) => {
  test.setTimeout(240000);
  await page.addInitScript(() => localStorage.setItem("zhepage-guide-seen-v1", "1"));
  await page.goto("/#zhepage-pairing=browser-test-pairing-code-only-not-a-real-secret");
  await expect(mainEditor(page)).toBeVisible();
  await importRichArticle(page, shortArticleHtml, shortTitle + shortBody);
  await expectPreviewReady(page);
  await page.getByRole("button", { name: "同步草稿", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "同步到平台草稿", exact: true });
  await dialog.getByRole("button", { name: "用当前海报开始", exact: true }).click();
  await expect(dialog.locator(".draft-sync-image-card").first()).toBeVisible({ timeout: 110000 });
  await dialog.getByRole("button", { name: "下一步：选择账号", exact: true }).click();
  await expect(dialog.getByText("本机同步已就绪", { exact: true })).toBeVisible();
  const beginLogin = dialog.getByRole("button", { name: "打开小红书登录窗口", exact: true });
  await beginLogin.click();
  await expect(dialog.getByRole("button", { name: "取消登录", exact: true })).toBeVisible();
  await expect(beginLogin).toBeDisabled();
  await dialog.getByRole("navigation", { name: "草稿保存步骤" }).getByRole("button", { name: "确认内容", exact: true }).click();
  await dialog.getByLabel("小红书标题", { exact: true }).fill("扫码期间仍可编辑");
  const cancelled = page.waitForResponse((response) => response.url().endsWith("/api/accounts/cancel-login") && response.request().method() === "POST");
  await dialog.getByRole("button", { name: "取消登录", exact: true }).click();
  expect(await (await cancelled).json()).toEqual({ cancelled: true });
  await expect(dialog.getByRole("button", { name: "取消登录", exact: true })).toHaveCount(0);
  await expect(dialog.getByLabel("小红书标题", { exact: true })).toHaveValue("扫码期间仍可编辑");
  await dialog.getByRole("button", { name: "下一步：选择账号", exact: true }).click();
  await beginLogin.click();
  await expect(dialog.getByRole("button", { name: "取消登录", exact: true })).toBeVisible();
  const closedLogin = page.waitForResponse((response) => response.url().endsWith("/api/accounts/cancel-login") && response.request().method() === "POST");
  await dialog.getByRole("button", { name: "关闭草稿同步", exact: true }).click();
  expect(await (await closedLogin).json()).toEqual({ cancelled: true });
  await expect(dialog).not.toBeVisible();
  await page.getByRole("button", { name: "同步草稿", exact: true }).click();
  await expect(beginLogin).toBeEnabled();
  await expect(dialog.getByRole("button", { name: "取消登录", exact: true })).toHaveCount(0);
});
