import { expect, test } from "@playwright/test";
import { makePng } from "./fixtures";
import { CLOUD_ORIGIN, PLATFORM_SECRET, SERVICE_PASSWORD, addCloudWechat, addCloudXhs, cloudPlatform, cloudState, cloudStep, connectCloud, credentialState, openCloudDialog, prepareCloudDraft } from "../helpers/cloud-sync";

test.use({ baseURL: CLOUD_ORIGIN, ignoreHTTPSErrors: true });

test("remembered encrypted accounts survive reload and the real cloud receives generated PNGs", async ({ page, context }, testInfo) => {
  test.setTimeout(240000);
  const submitted: { envelope: string; images: { base64: string }[] }[] = [];
  const browserApiOrigins: string[] = [];
  page.on("request", (request) => {
    if (!new URL(request.url()).pathname.startsWith("/api/sync/")) return;
    browserApiOrigins.push(new URL(request.url()).origin);
    if (request.method() === "POST" && request.url().endsWith("/api/sync/jobs")) submitted.push(request.postDataJSON());
  });
  let dialog = await prepareCloudDraft(page);
  await cloudPlatform(dialog, "wechat");
  await dialog.getByLabel("公众号贴图标题", { exact: true }).fill("云端 HTTP 整链路");
  await dialog.getByLabel("公众号贴图文案", { exact: true }).fill("实际生成图片通过同源接口交给测试平台。");
  await connectCloud(dialog);
  const account = await addCloudWechat(dialog, "记住的测试公众号", "wx1234567890abcdef");
  await account.check();
  await dialog.getByRole("button", { name: "存到本机", exact: true }).click();
  await expect(dialog.getByText("图片、文案和账号选择已存到当前浏览器", { exact: true })).toBeVisible();
  const saved = await credentialState(page);
  expect(saved.credentials).toHaveLength(1);
  expect(saved.credentials[0].envelope).toMatch(/^Fe26\.2\*/);
  expect(saved.pending).toEqual([]);
  for (const secret of [PLATFORM_SECRET, SERVICE_PASSWORD]) expect(saved.serialized).not.toContain(secret);
  const serviceCookie = (await context.cookies(CLOUD_ORIGIN)).find((cookie) => cookie.name === "__Host-zhepage_sync");
  expect(serviceCookie).toMatchObject({ secure: true, httpOnly: true, sameSite: "Strict", path: "/" });
  expect(serviceCookie!.expires).toBeGreaterThan(Date.now() / 1000 + 28 * 24 * 60 * 60);
  expect(await page.evaluate(() => document.cookie)).not.toContain("__Host-zhepage_sync");

  await page.reload();
  dialog = await openCloudDialog(page);
  await dialog.getByRole("button", { name: "继续本机存档", exact: true }).click();
  await cloudStep(dialog, "选择账号");
  await cloudPlatform(dialog, "wechat");
  await expect(dialog.getByText("网页同步服务已连接", { exact: true })).toBeVisible();
  await expect(dialog.getByRole("checkbox", { name: "选择同步账号 记住的测试公众号", exact: true })).toBeChecked();
  expect((await cloudState(page)).verifications).toBe(1);
  const submit = dialog.getByRole("button", { name: "存到 1 个账号草稿", exact: true });
  await expect(submit).toBeDisabled();
  await dialog.getByRole("checkbox", { name: "我已核对图片，沿用当前尺寸和比例", exact: true }).check();
  let releaseSave!: () => void;
  const gate = new Promise<void>((resolve) => { releaseSave = resolve; });
  await page.route("**/api/sync/jobs", async (route) => { await gate; await route.continue(); });
  await submit.click();
  try {
    await expect.poll(() => submitted.length).toBe(1);
    await expect(dialog.getByRole("button", { name: "关闭草稿同步", exact: true })).toBeDisabled();
    await expect(dialog.getByRole("button", { name: "返回选择账号", exact: true })).toBeDisabled();
    await expect(dialog.getByRole("navigation").getByRole("button", { name: "确认内容", exact: true })).toBeDisabled();
    await dialog.press("Escape");
    await expect(dialog).toBeVisible();
  } finally { releaseSave(); }
  await expect(dialog.getByText("已保存平台草稿", { exact: true })).toBeVisible();
  await expect(dialog.getByText("草稿编号：test-only-wechat-draft-1", { exact: true })).toBeVisible();
  const state = await cloudState(page);
  expect(state.saves).toHaveLength(1);
  expect(state.saves[0].content).toEqual({ title: "云端 HTTP 整链路", body: "实际生成图片通过同源接口交给测试平台。" });
  expect(state.saves[0].images[0]).toMatchObject({ mime: "image/png", width: 1080, height: 1440 });
  expect(state.saves[0].images[0].bytes).toBeGreaterThan(10000);
  expect(submitted).toHaveLength(1);
  expect(submitted[0].envelope).toBe(saved.credentials[0].envelope);
  const png = Buffer.from(submitted[0].images[0].base64, "base64");
  expect(png.subarray(0, 8).toString("hex")).toBe("89504e470d0a1a0a");
  expect(png.readUInt32BE(16)).toBe(1080);
  expect(png.readUInt32BE(20)).toBe(1440);
  expect(new Set(browserApiOrigins)).toEqual(new Set([CLOUD_ORIGIN]));
  expect((await credentialState(page)).pending).toEqual([]);
  await dialog.getByRole("button", { name: "返回选择账号", exact: true }).click();
  await expect(dialog.getByRole("checkbox", { name: "选择同步账号 记住的测试公众号", exact: true })).not.toBeChecked();
  await dialog.getByRole("button", { name: "查看保存结果", exact: true }).click();
  await testInfo.attach("cloud-draft-receipt", { body: await page.screenshot(), contentType: "image/png" });
});

test("platform limits and remembered pending locks govern ordered multi-account saves across reload", async ({ page }) => {
  test.setTimeout(300000);
  let dialog = await prepareCloudDraft(page);
  await dialog.getByLabel("小红书标题", { exact: true }).fill("小红书独立标题");
  await dialog.getByLabel("小红书文案", { exact: true }).fill("小红书独立配文");
  await cloudPlatform(dialog, "wechat");
  await dialog.getByLabel("公众号贴图标题", { exact: true }).fill("公众号独立标题");
  await dialog.getByLabel("公众号贴图文案", { exact: true }).fill("公众号独立配文");
  await connectCloud(dialog);
  await (await addCloudXhs(dialog, "首个小红书账号")).check();
  await (await addCloudWechat(dialog, "待核实公众号", "wx2222222222222222")).check();
  await (await addCloudWechat(dialog, "后续公众号", "wx3333333333333333")).check();
  let submit = dialog.getByRole("button", { name: /^存到 \d+ 个账号草稿$/ });
  await expect(submit).toHaveText("存到 3 个账号草稿");
  await expect(submit).toBeDisabled();
  await dialog.getByRole("checkbox", { name: "我已核对图片，沿用当前尺寸和比例", exact: true }).check();
  await expect(submit).toBeEnabled();
  for (const [platform, label, title, body] of [
    ["xiaohongshu", "小红书", "小红书独立标题", "小红书独立配文"],
    ["wechat", "公众号贴图", "公众号独立标题", "公众号独立配文"],
  ] as const) {
    await cloudStep(dialog, "确认内容");
    await cloudPlatform(dialog, platform);
    await dialog.getByLabel(`${label}标题`, { exact: true }).fill("甲".repeat(21));
    await expect(dialog.getByText("21 / 20 个字符（本工具上限）", { exact: true })).toBeVisible();
    await cloudStep(dialog, "选择账号");
    await expect(submit).toBeDisabled();
    await expect(dialog.getByRole("region", { name: "同步前检查" })).toContainText(`${label}标题最多 20 个字符`);
    await cloudStep(dialog, "确认内容");
    await dialog.getByLabel(`${label}标题`, { exact: true }).fill("甲".repeat(20));
    await cloudStep(dialog, "选择账号");
    await expect(submit).toBeEnabled();
    await cloudStep(dialog, "确认内容");
    await dialog.getByLabel(`${label}标题`, { exact: true }).fill(title);
    await dialog.getByLabel(`${label}文案`, { exact: true }).fill(Array.from({ length: 11 }, (_, index) => `#话题${index + 1}`).join(" "));
    await expect(dialog.getByText("话题 11 / 10 个；每个话题以 # 开头，用空格分隔", { exact: true })).toBeVisible();
    await cloudStep(dialog, "选择账号");
    await expect(submit).toBeDisabled();
    await expect(dialog.getByRole("region", { name: "同步前检查" })).toContainText(`${label}文案最多 10 个话题`);
    expect((await cloudState(page)).saves).toEqual([]);
    await cloudStep(dialog, "确认内容");
    await dialog.getByLabel(`${label}文案`, { exact: true }).fill(Array.from({ length: 10 }, (_, index) => `#话题${index + 1}`).join(" "));
    await cloudStep(dialog, "选择账号");
    await expect(submit).toBeEnabled();
    await cloudStep(dialog, "确认内容");
    await dialog.getByLabel(`${label}文案`, { exact: true }).fill(body);
    await cloudStep(dialog, "选择账号");
  }
  const persisted = await credentialState(page);
  expect(persisted.credentials).toHaveLength(3);
  expect(persisted.serialized).not.toContain("synthetic-xhs-session-secret-only");
  expect(persisted.serialized).not.toContain(PLATFORM_SECRET);
  await submit.click();
  await expect(dialog.getByText("已保存平台草稿", { exact: true })).toBeVisible();
  await expect(dialog.getByText("待核实", { exact: true })).toBeVisible();
  await expect(dialog.locator(".draft-sync-footer-status")).toContainText("已暂停后续账号");
  const firstSaves = (await cloudState(page)).saves;
  expect(firstSaves.map((save) => save.displayName)).toEqual(["首个小红书账号 · 测试创作者", "待核实公众号"]);
  expect(firstSaves.map((save) => save.content)).toEqual([{ title: "小红书独立标题", body: "小红书独立配文" }, { title: "公众号独立标题", body: "公众号独立配文" }]);
  expect(firstSaves[0].images).toEqual(firstSaves[1].images);
  expect((await credentialState(page)).pending).toHaveLength(1);
  await dialog.getByRole("button", { name: "存到本机", exact: true }).click();
  await expect(dialog.getByText("图片、文案和账号选择已存到当前浏览器", { exact: true })).toBeVisible();
  await page.reload();
  dialog = await openCloudDialog(page);
  await dialog.getByRole("button", { name: "继续本机存档", exact: true }).click();
  await cloudStep(dialog, "选择账号");
  await cloudPlatform(dialog, "wechat");
  await expect(dialog.getByText("网页同步服务已连接", { exact: true })).toBeVisible();
  await expect(dialog.getByRole("checkbox", { name: "选择同步账号 待核实公众号", exact: true }).locator("..")).toContainText("上次结果待核实");
  await expect(dialog.getByRole("button", { name: "从此浏览器移除加密授权包 待核实公众号", exact: true })).toBeDisabled();
  submit = dialog.getByRole("button", { name: /^存到 \d+ 个账号草稿$/ });
  await dialog.getByRole("checkbox", { name: "我已核对图片，沿用当前尺寸和比例", exact: true }).check();
  await expect(submit).toBeDisabled();
  await dialog.getByRole("button", { name: "刷新账号", exact: true }).click();
  await expect(submit).toBeDisabled();
  expect((await cloudState(page)).saves).toHaveLength(2);
  await dialog.getByRole("button", { name: "查看保存结果", exact: true }).click();
  const pendingReceipt = dialog.getByRole("article", { name: "待核实公众号的同步结果", exact: true });
  await expect(pendingReceipt.getByText("待核实", { exact: true })).toBeVisible();
  await pendingReceipt.getByRole("button", { name: "已在平台核对，确认已保存", exact: true }).click();
  await expect(pendingReceipt.getByText("用户确认已保存", { exact: true })).toBeVisible();
  await expect(pendingReceipt).toContainText("同步服务未自动验证");
  expect((await credentialState(page)).pending).toEqual([]);
  expect((await cloudState(page)).saves).toHaveLength(2);
  await dialog.getByRole("button", { name: "返回选择账号", exact: true }).click();
  await expect(submit).toHaveText("存到 1 个账号草稿");
  await expect(submit).toBeEnabled();
  await submit.click();
  await expect(dialog.getByText("草稿编号：test-only-wechat-draft-3", { exact: true })).toBeVisible();
  expect((await cloudState(page)).saves.map((save) => save.displayName)).toEqual(["首个小红书账号 · 测试创作者", "待核实公众号", "后续公众号"]);
});

test("the in-page QR image can be cancelled without freezing editing or opening a local browser", async ({ page, context }) => {
  test.setTimeout(240000);
  await page.setViewportSize({ width: 390, height: 844 });
  const dialog = await prepareCloudDraft(page, "waiting");
  await connectCloud(dialog);
  const login = dialog.getByRole("button", { name: "显示小红书登录二维码", exact: true });
  await login.click();
  const progress = dialog.getByRole("region", { name: "账号连接进度", exact: true });
  const qr = dialog.getByRole("img", { name: "小红书临时登录页面，请使用手机扫码", exact: true });
  await expect(progress.getByText("请用小红书扫描本页二维码", { exact: true })).toBeVisible();
  await expect(qr).toBeVisible();
  await expect.poll(() => qr.evaluate((node) => (node as HTMLImageElement).naturalWidth)).toBe(256);
  expect(context.pages()).toHaveLength(1);
  await expect(login).toBeDisabled();
  await cloudStep(dialog, "确认内容");
  await dialog.getByLabel("小红书标题", { exact: true }).fill("扫码期间仍可编辑");
  await dialog.getByLabel("小红书文案", { exact: true }).fill("编辑内容不会因等待扫码丢失。");
  const count = await dialog.locator(".draft-sync-image-card").count();
  await dialog.getByLabel("草稿图片文件", { exact: true }).setInputFiles({ name: "during-qr.png", mimeType: "image/png", buffer: makePng(70, 90, 130) });
  await expect(dialog.locator(".draft-sync-image-card")).toHaveCount(count + 1);
  await dialog.locator(".draft-sync-image-card").last().getByRole("button", { name: /^删除/ }).click();
  await dialog.getByRole("button", { name: "存到本机", exact: true }).click();
  await expect(dialog.getByText("图片、文案和账号选择已存到当前浏览器", { exact: true })).toBeVisible();
  let cancelCalls = 0;
  await page.route("**/api/sync/logins/*/cancel", async (route) => {
    cancelCalls++;
    if (cancelCalls === 1) await route.fulfill({ status: 502, contentType: "application/json", body: JSON.stringify({ error: "暂未确认取消，请再试一次" }) });
    else await route.continue();
  });
  await progress.getByRole("button", { name: "取消登录", exact: true }).click();
  await expect(progress.getByRole("alert")).toContainText("暂未确认取消");
  await expect(dialog.getByLabel("小红书标题", { exact: true })).toBeEnabled();
  await cloudStep(dialog, "选择账号");
  await expect(login).toBeDisabled();
  expect((await cloudState(page)).activeRuntimes).toBe(1);
  const cancelled = page.waitForResponse((response) => response.url().endsWith("/cancel") && response.request().method() === "POST" && response.ok());
  await progress.getByRole("button", { name: "取消登录", exact: true }).click();
  expect(await (await cancelled).json()).toEqual({ cancelled: true });
  await expect(progress).toHaveCount(0);
  await expect(qr).toHaveCount(0);
  await expect(login).toBeEnabled();
  await expect.poll(async () => (await cloudState(page)).activeRuntimes).toBe(0);
  await cloudStep(dialog, "确认内容");
  await expect(dialog.getByLabel("小红书标题", { exact: true })).toHaveValue("扫码期间仍可编辑");
  await cloudStep(dialog, "选择账号");
  await login.click();
  await expect(qr).toBeVisible();
  await dialog.getByRole("button", { name: "关闭草稿同步", exact: true }).click();
  await expect(dialog).toBeHidden();
  await openCloudDialog(page);
  await expect(login).toBeEnabled();
  await expect(progress).toHaveCount(0);
  const state = await cloudState(page);
  expect(state).toMatchObject({ loginStarts: 2, activeRuntimes: 0, closedRuntimes: 2, saves: [] });
  expect((await credentialState(page)).credentials).toEqual([]);
});

test("forgetting an account on reload preserves its unresolved save until reconnect and manual acknowledgement", async ({ page }) => {
  test.setTimeout(240000);
  let dialog = await prepareCloudDraft(page);
  await cloudPlatform(dialog, "wechat");
  await dialog.getByLabel("公众号贴图标题", { exact: true }).fill("不记住授权也保留核对记录");
  await connectCloud(dialog, false);
  await (await addCloudWechat(dialog, "待核实临时账号", "wx4444444444444444")).check();
  await dialog.getByRole("button", { name: "存到本机", exact: true }).click();
  await expect(dialog.getByText("图片、文案和账号选择已存到当前浏览器", { exact: true })).toBeVisible();
  await dialog.getByRole("checkbox", { name: "我已核对图片，沿用当前尺寸和比例", exact: true }).check();
  await dialog.getByRole("button", { name: "存到 1 个账号草稿", exact: true }).click();
  await expect(dialog.getByText("待核实", { exact: true })).toBeVisible();
  expect((await credentialState(page)).credentials).toEqual([]);
  expect((await credentialState(page)).pending).toHaveLength(1);
  await page.reload();
  dialog = await openCloudDialog(page);
  await dialog.getByRole("button", { name: "继续本机存档", exact: true }).click();
  await cloudStep(dialog, "选择账号");
  await cloudPlatform(dialog, "wechat");
  await expect(dialog.getByText("网页同步服务已连接", { exact: true })).toBeVisible();
  await expect(dialog.getByRole("button", { name: "存到 1 个账号草稿", exact: true })).toBeDisabled();
  await dialog.getByRole("button", { name: "查看保存结果", exact: true }).click();
  await expect(dialog.getByRole("button", { name: "已在平台核对，确认未保存", exact: true })).toBeDisabled();
  expect((await cloudState(page)).saves).toHaveLength(1);
  await cloudStep(dialog, "选择账号");
  await addCloudWechat(dialog, "待核实临时账号", "wx4444444444444444");
  await expect(dialog.getByRole("button", { name: "存到 1 个账号草稿", exact: true })).toBeDisabled();
  await dialog.getByRole("button", { name: "查看保存结果", exact: true }).click();
  await dialog.getByRole("button", { name: "已在平台核对，确认未保存", exact: true }).click();
  await expect(dialog.getByText("未保存", { exact: true })).toBeVisible();
  await expect(dialog.getByRole("article", { name: "待核实临时账号的同步结果", exact: true })).toContainText("尚未再次发送");
  expect((await credentialState(page)).pending).toEqual([]);
  expect((await cloudState(page)).saves).toHaveLength(1);
});
